name: pookaboo
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.0
  logger: ^2.1.0

  # local storage
  hive_flutter: ^1.1.0

  # Freezed
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # supabase
  supabase_flutter: ^2.3.4

  # kakao
  kakao_map_plugin: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.8

  # Freezed
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


scripts:
  run: flutter run --dart-define-from-file=".env"
  build_l10n: flutter gen-l10n
  build_model: flutter packages pub run build_runner build --delete-conflicting-outputs  