name: pookaboo
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.0
  logger: ^2.1.0
  injectable: ^2.3.2

  # geo locator
  geolocator: ^11.0.0

  # Freezed
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # supabase
  supabase_flutter: ^2.3.4

  # kakao
  kakao_map_plugin: ^0.2.5
    # path: ../kakao_map_plugin/

  flutter_secure_storage: ^9.0.0

  # google
  google_sign_in: ^6.2.1

  # svg
  flutter_svg: ^2.0.10+1

  # bottom sheet 
  bottom_sheet: ^4.0.0

  # image swipe
  carousel_slider: ^4.2.1
  
  # blur
  blur: ^3.1.0

  # dio
  dio: ^5.4.1

  # kakao sdk
  kakao_flutter_sdk: ^1.9.0

  # platform
  platform: ^3.1.4
  crypto: ^3.0.3
  encrypt: ^5.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.8

  # Freezed
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # injectable
  injectable_generator: ^2.4.1

  # intl
  intl_generator: ^0.4.1

flutter:
  generate: true 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

  # example:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf

scripts:
  run: flutter run --dart-define-from-file=".env"
  build_l10n: flutter pub run intl_generator:generate_from_arb --output-dir=lib/shared/localization/generated --no-use-deferred-loading lib/main.dart lib/shared/localization/intl_*.arb
  build: flutter clean && flutter packages pub get &&  flutter packages pub run build_runner build --delete-conflicting-outputs